export const en = {
    en: {
        translation: {
            "Welcome to React": "Welcome to React and react-i18next",
            "ExampleEx": "example",
            "Search": "Search",
            "Add": "Add",
            "Submit": "Submit",
            "BankAccounts": "Bank Accounts",
            "Tills": "Tills",
            "PaymentTerms": "Payment Terms",
            "bankaccountcode": "Banka Kodu",
            "bankaccountname": "Bank Account Name",
            "bankcode": "Bank Code",
            "branchcode": "Branch Code",
            "currency": "Currency",
            "tillcode": "Till Code",
            "tillname": "Till Name",
            "paymenttermcode": "Payment Term Code",
            "paymenttermdesc": "Payment Term Description",
            "daycount": "Day Count",
            "active": "Active",
            "invoiceds": "Invoice Details",
            "explanation": "Explanation",
            "amount": "Amount",
            "itemtype": "Item Type",
            "itemcode": "Item Code",
            "unitprice": "Unit Price",
            "quantity": "Quantity",
            "netamount": "Net Amount",
            "stakeholdercode": "Stakeholder Code",
            "stakeholdername": "Stakeholder Name",
            "taxno": "Tax No",
            "invdate": "Invoice Date",
            "address": "Address",
            "itemname": "Item Name",
            "unitsale": "Unit Sale",
            "baseunit": "Base Unit",
            "amount": "Amount",
            "paymentterm": "Payment Term",
            "contactinformation": "Contact Information",
            "iname": "Name",
            "isurname": "Surname",
            "identityno": "Identity No",
            "country": "Country",
            "city": "City",
            "county": "County",
            "postcode": "Post Code",
            "phone": "Phone",
            "fax": "Fax No",
            "website": "Website",
            "contactname": "Contact Name",
            "contactemail": "Contact Mail",
            "contactmobile": "Contact Mobile",
            "contactphone": "Contact Phone",
            "contactrole": "Contact Role",
            "contactnotes": "Contact Notes",
            "risklimit": "Risk Limit",
            "Stakeholders": "Stakeholders",
            "Customers": "Customers",
            "suppliercode": "Supplier Code",
            "suppliername": "Supplier Name",
            "StockList": "Stock List",
            "StockTransactions": "Stock Transactions",
            "New": 'New',
            "ProductService": "Product/Service",
            "invoiceno": "Invoice No",
            "eiNo": "E-Invoice No",
            "invoicetype": "Invoice Type",
            "gtotalamount": "Total Amount",
            "paidamount": "Paid Amount",
            "MonetaryTransactions": "Monetary Transactions",
            "COLLECTION": "Collection",
            "PAYMENT": "Payment",
            "installmentperiod": "Installment Period",
            "installmentperiodunit": "Installment Period Unit",
            "initialpaymentdate": "Initial Payment Date",
            "installmentcount": "Installment Count",
            "day": "Day",
            "month": "Month",
            "paymentinformation": "Payment Information",
            "documentno": "Document No",
            "Sales": "Sales",
            "PurchaseInvoice": "Purchase Invoice",
            "SupplierCode": "Supplier Code",
            "SupplierName": "Supplier",
            "SubTotal": "Sub Total",
            "TotalDiscount": "Total Discount",
            "gTotal": "Grand Total",
            "Balance": "Balance",
            "AddPayment": "Add Payment",
            "Total": "Total",
            "SalesExtradite": "Sales Extradite",
            "ReferenceNo": "Reference No",
            "RemainingProduct": "Remaining Product",
            "serialno": "Serial No",
            "batchno": "BatchNo",
            "EntryDate": "Entry Date",
            "AvailableQty": "Available Quantity",
            "salesprice": "Sales Price",
            "vatcode": "VAT",
            "sctcode": "SCT",
            "pctcode": "PCT",
            "stockcontrol": "Stock Control",
            "minstockqty": "Minimum Stock Quantity",
            "maxstockqty": "Maximum Stock Quantity",
            "barcodeno": "Barcode No",
            "categoryid": "Category No",
            "stockmanagement": "Stock Management",
            "discountamount": "Discount Amount",
            "vatamount": "VAT Amount",
            "sctamount": "SCT Amount",
            "UnitSale": "Unit Sale",
            "Save": "Save",
            "SelectedAmount": "SelectedAmount",
            "Transactions": "TRANSACTIONS",
            "PurchasesExtradite": "Purchases Extradite",
            "physicalqty": "Physical Quantity",
            "variantid": "Variant Code",
            "collectionhistory": "Collection History",
            "currencylc": "Currency",
            "docdate": "Document Date",
            "InvoiceSummary": "Invoice Summary",
            "Remaining": "Remaining",
            "tillcode": "Till Code",
            "tillname": "Till Name",
            "status": "Status",
            "Active": "Active",
            "Inactive": "Inactive",
            "TillCodeIsRequired": "Till Code is required.",
            "bankaccountcode": "Bank Account Code",
            "bankaccountname": "Bank Account Name",
            "bankcode": "Bank Code",
            "branchcode": "Branch Code",
            "creditcard": "Credit Card",
            "accountno": "Account No",
            "ibanno": "Iban No",
            "paymenttermcode": "Payment Term Code",
            "paymenttermdesc": "Payment Term Description",
            "paymenttermtype": "Payment Term Type",
            "daycount": "Day Count",
            "PaymentTermCodeIsRequired": "Payment Term Code Is Required.",
            "BankAccountCodeIsRequired": "Bank Account Code Is Required.",
            "movementtypes": "Movement Types",
            "BuyerTillBankName": "Alıcı Kasa/Banka Adı",
            "MovementType": "Tahsilat Türü",
            "amountlc": "UP Tutar",
            "account": "Account",
            "itemexplanation": "Item Explanation",
            "Cash": "Cash",
            "Check": "Check",
            "Bond": "Bond",
            "BankTransferEFT": "BankTransferEFT",
            "movementtypeid": "Movement Type",
            "maturitydate": "Maturity Date",
            "ownercode": "Owner Code",
            "Lines": "Lines",
            "Explanation": "Explanation",
            "Document": "Document",

            "AddCollection": "ADD COLLECTION",
            "SendToGIB": "SEND TO GIB",
            "print": "PRINT",
            "transqty": "Trans Quantity ",
            "itemtypecode": "Item Type",
            "Service": "Service",
            "Update": "Update",
            "SaleInvoice": "Sale Invoice",
            "View": "View",
            "Save": "Save",
            "SalesExtradite": "Sales Extradite",
            "TotalPaidAmount": "Total Paid Amount",
            "TotalCollectionAmount": "Total Collection Amount",
            "collectionAmount": "Collection Amount",
            "paymentHistory": "Payment History",
            "PurchaseExtradite": "Purchase Extradite",
            "PurchaseInvoice": "Purchase Invoice",
            "paymentdate": "Payment Date",
            "paymenttype": "Payment Type",
            "unit": "Unit",
            "StockShipping": "Stock Shipping",
            "subscriptionsId": "Subscription Code",
            "companyName": "Subscription Name",
            "senderCode": "Sender Code",
            "sender": "Sender",
            "accdocno": "Document Number",
            "sendTime": "Send Time",
            "status": "Status",
            "Pending": "Pending",
            "senderexplanation": "Sender Explanation",
            "recipientexplanation": "Recipient Explanation",
            "Accept/Reject": "Accept/Reject",
            "YouMustAddExplanationOfTheRejected": "You must add explanation of the rejected",
            "Reject": "Reject",
            "Accept": "Accept",
            "Accept/RejectIsRequired": "Accept/Reject is required field.",
            "StockConfirmation": "Stock Confirmation",
            "GoodsConfirmation": "Goods Confirmation",
            "expensecategorydesc": "Expense Category",
            "expensecategoryid": "Expense Category",
            "expensename": "Expense Name",
            "expensecode": "Expense Code",
            "taxoffice": "Taxoffice",
            "stakeholdertype": "Stakeholder Type",
            "shipmenttime": "Shipment Time",
            "deliverynoteno": "Delivery Note No",
            "stocks": "Stocks",
            "StockBlockRequest": "Stock Block Request",
            "purchaseprice": "Purchase Price",
            "accdoctype": "Document Type",
            "dcindicator": "D/C",
            "credit": "Credit",
            "debit": "Debit",
            "PaymentCondition": "Payment Condition",
            "totalamount": "Total Amount",
            "AccountStatement": "Account Statement",
            "term": "Term",
            "PleaseSelectSupplier": "Please Select Supplier.",
            "PleaseSelectLine": "Please Select Line.",
            "PleaseSelectCustomer": "Please Select Customer.",
            "PleaseSelectMovementType": "Please Select Movement Type.",
            "PleaseSelectOwnerCode": "Please Select Owner Code.",
            "MaturityDateisRequired": "Maturity Date is Required.",
            "AmountisRequired": "Amount is Required.",
            "PleaseSelectStock": "Plase Select Stock.",
            "PleaseSelectItemCodeandStock": "Please Select Item Code and Stock.",
            "Individual": "Individual",
            "Corporate": "Corporate",
            "StakeholdernameisRequired": "Stakeholder Name is Required.",
            "IdentitynoisRequired": "Identity No is Required.",
            "PaymenttermisRequired": "Payment Term is Required.",
            "AddressisRequired": "Address is Required.",
            "CountyisRequired": "County is Required.",
            "PhoneisRequired": "Phone is Required.",
            "TaxnoisRequired": "Tax No is Required.",
            "companycode": "Company Code",
            "companyname": "Company Name",
            "taxno": "Tax No",
            "taxoffice": "Tax Office",
            "telno": "Telephone Number",
            "Companies": "Companies",
            "Variant": "Variant",
            "userDesc": "User Description",
            "upass": "Password",
            "upassR": "Password Repeat",
            "rolecode": "Role Code",
            "Users": "Users",
            "Roles": "Roles",
            "rolename": "Rol Adı",
            "createuser": "Create User",
            "createtime": "Create Time",
            "ExpensesCategory": "Expenses Category",
            "Expenses": "Expenses",
            "matdocno": "Document Number",
            "documentdate": "Document Date",
            "PaymentSituation": "Payment Situation",
            "ExpenseCode": "Expense Code",
            "ExpenseSlips": "Expense Slips",
            "Delete": "Delete",
            "V": "Supplier",
            "X": "Customer & Supplier",
            "C": "Customer",
            "transaction": "Transaction",
            "Login": "Login",
            "Password": "Password",
            "KULLANICI": "USER",
            "Pay": "PAY",
            "English": "English",
            "Turkish": "Turkish",
            "Logout": "Logout",
            "MyProfile": "My Profile",
            "Inbox": "Inbox",
            "RequiredFields": "Required Fields",
            "AdditionalFields": "Additional Fields",
            "Category": "Category",
            "SaleInvoice(Extradited)": "Sale Invoice(Extradited)",
            "AreYouSureYouWantToDelete": "Are you sure you want to delete?",
            "Yes": "Yes",
            "No": "No",
            "YouCannotBillMoreThan1WeekRetrospectively": "You cannot bill more than 7 days retrospectively.",
            "YouCannotBillForward": "You cannot bill forward.",
            "Cancel": "Cancel",
            "starttime": "Start Date",
            "endtime": "End Date",
            "nodata":"No Data",
            "equal":"Equal",
            "contains":"Contains",
            "suppliertype":"Supplier Type",
        }
    }
}