import { isMobile } from "../@mscComponnent/Global/GlobalFunc";

export const tr = {
    tr: {
        translation: {
            "Welcome to React": "Welcome to React and react-i18next",
            "ExampleEx": "örnek",
            "Search": "Ara",
            "Add": "Ekle",
            "Submit": "Gönder",
            "BankAccounts": "Banka Hesapları",
            "Tills": "Kasalar",
            "PaymentTerms": "Ödeme Koşulları",
            "bankaccountcode": "Banka Hesap Kodu",
            "bankaccountname": "Banka Hesap Adı",
            "bankcode": "Banka Kodu",
            "branchcode": "Şube Kodu",
            "currency": "Para Birimi",
            "tillcode": "Kasa Kodu",
            "tillname": "Kasa Adı",
            "paymentterm": "Ödeme Koşulu Kodu",
            "daycount": "Gün Sayısı",
            "active": "Aktiflik",
            "invoiceds": "Kalemler",
            "explanation": "Açıklama",
            "paymentdate": "Ödeme Tarihi",
            "unitprice": "Birim Fiyatı",
            "itemtype": "Ürün Tipi",
            "itemcode": "Ürün Kodu",
            "quantity": "Miktar",
            "netamount": "Net Tutar",
            "stakeholdercode": "Müşteri Kodu",
            "stakeholdername": "Müşteri Adı",
            "taxno": "Vergi Numarası",
            "invdate": "Fatura Tarihi",
            "address": "Adres",
            "itemname": "Ürün Adı",
            "unitsale": "Satış Birimi",
            "baseunit": "Temel Ölçü Birimi",
            "amount": "Tutar",
            "paymentterm": "Vade Periyodu",
            "contactinformation": "İletişim Bilgileri",
            "iname": "İsim",
            "isurname": "Soyisim",
            "identityno": "Kimlik Numarası",
            "country": "Ülke",
            "city": "Şehir",
            "county": "İlçe",
            "postcode": "Posta Kodu",
            "phone": "Telefon",
            "fax": "Fax No",
            "website": "Website",
            "contactname": "Kişi Adı",
            "contactemail": "Kişi Mail",
            "contactmobile": "Kişi Mobil",
            "contactphone": "Kişi Telefon",
            "contactrole": "Kişi Rolü",
            "contactnotes": "Kişi Notları",
            "risklimit": "Risk Limiti",
            "Suppliers": "Tedarikçiler",
            "Customers": "Müşteriler",
            "suppliercode": "Tedarikçi Kodu",
            "suppliername": "Tedarikçi Adı",
            "StockList": "Stok Listesi",
            "StockTransactions": "Stok Hareketleri",
            "New": 'Yeni',
            "ProductService": "Ürün/Hizmet",
            "invoiceno": "Fatura Numarası",
            "eiNo": "E-Fatura Numarası",
            "invoicetype": "Fatura Tipi",
            "gtotalamount": "Fatura Tutarı",
            "paidamount": "Ödenen Tutar",
            "MonetaryTransactions": "Parasal İşlemler",
            "COLLECTION": "Tahsilat",
            "PAYMENT": "Ödeme",
            "installmentperiod": "Ödeme Periyodu",
            "installmentperiodunit": "Ödeme Periyot Seçimi",
            "initialpaymentdate": "İlk Ödeme Tarihi",
            "installmentcount": "Taksit Sayısı",
            "day": "Gün",
            "month": "Ay",
            "paymentinformation": "Ödeme Bilgileri",
            "documentno": "Döküman Numarası",
            "discountamount": "İndirim Tutarı",
            "vatcode": "KDV",
            "vatamount": "KDV Tutarı",
            "sctcode": "ÖTV",
            "sctamount": "ÖTV Tutarı",
            "netamount": "Net Tutar",
            "Sales": "Satışlar",
            "PurchaseInvoice": "Alış Faturası",
            "SupplierCode": "Tedarikçi Kodu",
            "SupplierName": "Tedarikçi",
            "SubTotal": "Ara Toplam",
            "TotalDiscount": "Toplam İndirim",
            "gTotal": "Genel Toplam",
            "Balance": "Bakiye",
            "AddPayment": "Ödeme Ekle",
            "Total": "Toplam",
            "SalesExtradite": "Satış İade",
            "ReferenceNo": "Referans Numarası",
            "RemainingProduct": "Kalan Ürün Adeti",
            "serialno": "Seri Numarası",
            "batchno": "Parti Numarası",
            "EntryDate": "Giriş Tarihi",
            "AvailableQty": "Kullanılabilir Miktar",
            "UnitSale": "Satış Birimi",
            "Save": "KAYDET",
            "SelectedAmount": "Seçilen Miktar",
            "Transactions": "İŞLEMLER",
            "PurchasesExtradite": "Alış İade Faturası",
            "physicalqty": "Fiziksel Miktar",
            "variantid": "Varyant Kodu",
            "collectionhistory": "Tahsilat Geçmişi",
            "accdocno": "Belge Numarası",
            "amountlc": "Tahsil Edilen Tutar",
            "currencylc": "Para Birimi",
            "docdate": "Tahsilat Tarihi",
            "InvoiceSummary": "Fatura Özeti",
            "Remaining": "Kalan",
            "tillcode": "Kasa Kodu",
            "tillname": "Kasa Adı",
            "status": "Durum",
            "Active": "Etkin",
            "Inactive": "Etkin Değil",
            "TillCodeIsRequired": "Kasa Kodu alanı zorunludur.",
            "bankaccountcode": "Banka Hesap Kodu",
            "bankaccountname": "Banka Hesap Adı",
            "bankcode": "Banka Kodu",
            "branchcode": "Şube Kodu",
            "creditcard": "Kredi Kartı",
            "accountno": "Hesap Numarası",
            "ibanno": "Iban Numarası",
            "paymenttermcode": "Ödeme Koşulu Kodu",
            "paymenttermdesc": "Ödeme Koşulu Açıklaması",
            "paymenttermtype": "Ödeme Koşulu Tipi",
            "daycount": "Gün Sayısı",
            "PaymentTermCodeIsRequired": "Ödeme Koşulu Kodu alanı zorunludur.",
            "BankAccountCodeIsRequired": "Banka Hesap Kodu alanı zorunludur.",
            "movementtypes": "Tahsilat Türü",
            "BuyerTillBankName": "Alıcı Kasa/Banka Adı",
            "amountlc": "UP Tutar",
            "account": "Hesap",
            "itemexplanation": "Kalem Açıklaması",
            "Cash": "Nakit",
            "Check": "Çek",
            "Bond": "Senet",
            "BankTransferEFT": "Bankaya(Havale/EFT)",
            "movementtypeid": "Ödeme Türü",
            "maturitydate": "Vade Tarihi",
            "ownercode": "Hesap",
            "Lines": "Kalemler",
            "Explanation": "Açıklama",
            "Document": "Doküman",
            "AddCollection": "TAHSİLAT EKLE",
            "SendToGIB": "GIB'E GÖNDER",
            "print": "YAZDIR",
            "transqty": "Miktar",
            "itemtypecode": "Ürün Tipi",
            "Service": "Hizmet",
            "Update": "Düzenle",
            "SaleInvoice": "Satış Faturası",
            "View": "Görüntüle",
            "TotalPaidAmount": "Toplam Ödenen Tutar",
            "TotalCollectionAmount": "Toplam Tahsil Edilen Tutar",
            "collectionAmount": "Tahsilat Tutarı",
            "paymentHistory": "Ödeme Geçmişi",
            "PurchaseExtradite": "Alış İade",
            "PurchaseInvoice": "Alış Faturası",
            "paymentdate": "Ödeme Tarihi",
            "paymenttype": "Ödeme Türü",
            "unit": "Birim",
            "StockShipping": "Stok Gönderimi",
            "subscriptionsId": "Bayi Kodu",
            "companyName": "Bayi Adı",
            "senderCode": "Gönderen Kodu",
            "sender": "Gönderen",
            "sendTime": "Gönderme Zamanı",
            "status": "Durum",
            "Pending": "Beklemede",
            "senderexplanation": "Gönderen Açıklama",
            "recipientexplanation": "Alıcı Açıklama",
            "Accept/Reject": "Kabul/Red",
            "YouMustAddExplanationOfTheRejected": "Redlenen stok için açıklama eklemelisiniz.",
            "Reject": "Red",
            "Accept": "Kabul",
            "Accept/RejectIsRequired": "Kabul/Red alanı zorunludur.",
            "StockConfirmation": "Stok Kabul",
            "GoodsConfirmation": "Mal Kabul",
            "expensecategorydesc": "Gider Kategorileri",
            "expensecategoryid": "Gider Kategorileri",
            "expensename": "Gider Adı",
            "expensecode": "Gider Kodu",
            "taxoffice": "Vergi Dairesi",
            "stakeholdertype": "Müşteri Tipi",
            "shipmenttime": "Sevk Tarihi",
            "deliverynoteno": "İrsaliye Numarası",
            "stocks": "Stoklar",
            "StockBlockRequest": "Stok Blok Talebi",
            "purchaseprice": "Alış Fiyatı",
            "salesprice": "Satış Fiyatı",
            "stockmanagement": "Stok Yönetimi",
            "categoryid": "Kategori Numarası",
            "barcodeno": "Barkod Numarası",
            "stockcontrol": "Stok Kontrolü",
            "pctcode": "ÖİV",
            "minstockqty": "Minimum Stok Miktarı",
            "maxstockqty": "Maximum Stok Miktarı",
            "accdoctype": "Belge Tipi",
            "dcindicator": "B/A",
            "credit": "Alacak",
            "debit": "Borç",
            "PaymentCondition": "Ödeme Koşulu",
            "totalamount": "Toplam Tutar",
            "Filter": "Filtrele",
            "AccountStatement": "Hesap Ekstresi",
            "term": "Vadeli",
            "PleaseSelectSupplier": "Lütfen tedarikçi seçiniz.",
            "PleaseSelectLine": "Lütfen kalem giriniz.",
            "PleaseSelectCustomer": "Lütfen müşteri seçiniz.",
            "PleaseSelectMovementType": "Lütfen tahsilat/ödeme türü seçiniz.",
            "PleaseSelectOwnerCode": "Lütfen hesap seçiniz.",
            "MaturityDateisRequired": "Vade tarihi alanı zorunludur.",
            "AmountisRequired": "Tutar alanı zorunludur.",
            "PleaseSelectStock": "Lütfen stok giriniz.",
            "PleaseSelectItemCodeandStock": "Lütfen ürün kodu ve stok seçiniz.",
            "Individual": "Bireysel",
            "Corporate": "Kurumsal",
            "StakeholdernameisRequired": "Müşteri adı alanı zorunludur.",
            "IdentitynoisRequired": "Kimlik numarası alanı zorunludur.",
            "PaymenttermisRequired": "Vade periyodualanı zorunludur.",
            "AddressisRequired": "Adres alanı zorunludur.",
            "CountyisRequired": "İlçe alanı zorunludur.",
            "PhoneisRequired": "Telefon alanı zorunludur.",
            "TaxnoisRequired": "Vergi Numarası alanı zorunludur.",
            "companycode": "Şirket Kodu",
            "companyname": "Şirket Adı",
            "taxno": "Vergi Numarası",
            "taxoffice": "Vergi Dairesi",
            "telno": "Telefon Numarası",
            "Companies": "Şirketler",
            "variant": "Varyant",
            "userDesc": "Kullanıcı Açıklaması",
            "upass": "Şifre",
            "upassR": "Şifre Tekrar",
            "rolecode": "Rol Kodu",
            "Users": "Kullanıcılar",
            "Roles": "Roller",
            "rolename": "Rol Adı",
            "createuser": "Oluşturan Kullanıcı",
            "createtime": "Oluşturma Zamanı",
            "ExpensesCategory": "Giderler Kategorisi",
            "Expenses": "Giderler",
            "matdocno": "Belge Numarası",
            "documentdate": "Belge Tarihi",
            "PaymentSituation": "Ödeme Durumu",
            "ExpenseCode": "Gider Kodu",
            "ExpenseSlips": "Gider Fişleri",
            "Delete": "Sil",
            "V": "Tedarikçi",
            "X": "Hem Tedarikçi Hem Müşteri",
            "C": "Müşteri",
            "transaction": "İşlem",
            "Login": "Giriş",
            "Password": "Şifre",
            "ADMINISTRATOR": "YÖNETİCİ",
            "KULLANICI": "KULLANICI",
            "Pay": isMobile() ? "ÖDEME" : "ÖDEME YAP",
            "English": "İngilizce",
            "Turkish": "Türkçe",
            "Logout": "Çıkış Yap",
            "MyProfile": "Profilim",
            "Inbox": "Gelen Kutusu",
            "CreateCustomer": "Müşteri Oluştur",
            "RequiredFields": "Zorunlu Alanlar",
            "AdditionalFields": "Ek Alanlar",
            "Category": "Kategori",
            "SaleInvoice(Extradited)": "Satış Faturası(İadeEdildi)",
            "AreYouSureYouWantToDelete": "Silmek istediğinize emin misiniz?",
            "Yes": "Evet",
            "No": "Hayır",
            "YouCannotBillMoreThan1WeekRetrospectively": "7 günden fazla geriye dönük fatura kesemezsiniz.",
            "YouCannotBillForward": "İleriye Dönük fatura kesemezsiniz.",
            "Cancel": "İptal",
            "starttime": "Başlangıç Tarihi",
            "endtime": "Bitiş Tarihi",
            "nodata":"Veri Yok",
            "equal":"Eşittir",
            "contains":"İçerir",
            "suppliertype":"Tedarikçi Tipi",
            
        }
    }
}